### ISSUE TITLE
Can't get enews module working :-)

### ISSUE THREAD

**Issue by blundell** [novoda/spikes#127]
https://github.com/novoda/spikes/tree/master/enews

I can't work out how to run the enews html generator.

i have Intellij Ultiimate edition with the node plugin.

When I run the `demo.js` I get:

```
Error: Cannot find module 'enews-fetcher'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/blundell/Dev/git-repo/spikes/enews/html-generator-node/demo.js:1:82)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

Can you update the readme for the module / modules to explain how I import it into Inteillj and what magic build config settings I have to add?

**Comment by blundell** [comment]
deprecated
